name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes com pytest
        run: pytest

  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push da imagem
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app_test_prova:${{ github.run_number }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app_test_prova:${{ github.run_number }}

      - name: Atualizar kustomization.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          sed -i "s|newTag:.*|newTag: ${{ github.run_number }}|" k8s/kustomization.yaml
          git add k8s/kustomization.yaml
          git commit -m "ci: atualiza imagem para versão ${{ github.run_number }}"
          git push